// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using console.analise_credito.src.Data;

#nullable disable

namespace console.analise_credito.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("console.analise_credito.src.Models.AvaliacaoCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AvalidoEm")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RendaMensal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorCreditoOferecido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("estaElegivel")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("AvaliacoesClientes");
                });
#pragma warning restore 612, 618
        }
    }
}
